-- Create Users Table in Supabase (PostgreSQL)
create table if not exists users (
    id bigint generated by default as identity primary key,
    email text unique not null,
    username text unique,
    password_hash text,
    otp text,
    otp_expiry timestamp
    with
        time zone,
        created_at timestamp
    with
        time zone default now()
);

-- Enable Row Level Security (RLS) is recommended but optional for this simple backend implementation
-- alter table users enable row level security;`