-- Create users table in Supabase (PostgreSQL)
create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email text unique not null,
    username text unique,
    password_hash text,
    otp text,
    otp_expiry timestamptz,
    created_at timestamptz default now()
);

-- Optional: if you enable RLS, backend should use service-role key for server writes/reads.
-- alter table public.users enable row level security;
